### ISSUE TITLE
Allow configuring the cache location

### ISSUE THREAD

**Issue by cachapa** [cachapa/AerialDream#17]

**Comment by ns5gti** [comment]
Looking forward to this option.

Thanks

**Comment by spookyUnknownUser** [comment]
Me 2, this will be great for my Nexus player, only has a couple gb of
storage.

**Comment by secret-liar** [comment]
Hello! 

Sorry I can't help and I see that you are looking for some.

I just wanted to add my voice to tell you that I'd love this option! I have a NAS running 24/24 and would love to cache aerial videos on it :D

**Comment by cachapa** [comment]
Caching is disabled for now as it wasn't working properly.
I might revisit this later but for now I'm closing this ticket since the solution will probably require a complete rewrite of the caching system anyway.
