### ISSUE TITLE
Add 2018 Apple TV videos

### ISSUE THREAD

**Issue by uratrtl** [cachapa/AerialDream#18]
Hi, I was wondering if there are any plans to add the newer apple tv "scenes" to this wonderful app?

**Comment by cachapa** [comment]
Do you have a source for those videos?

**Comment by uratrtl** [comment]
I have an apple tv and a shield so I have access in that way. Ill see if I can find direct video for it

**Comment by cachapa** [comment]
Just to be clear, currently Aerial Dream loads the Apple videos. There are two playlists: the original HD videos and the 4K which were released about 1 year ago.

I'm not aware of a new playlist. If there's one and it's freely available, then I'd be happy to add it to the app.

**Comment by uratrtl** [comment]
https://www.reddit.com/r/apple/comments/771n8q/download_links_for_the_4k_apple_tv_screensavers/?st=jn4yhwlz&sh=6460bcb1 
or
http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers
or 
http://benjaminmayo.co.uk/scripts/apple-tv-screensavers.json

I might just be confusing it but I thought there was that new ISS scene. Is there anyway to force load the 4k screensaver to 1080? It would be nice to have the new scenes.

**Comment by cachapa** [comment]
If I'm not mistaken those are exactly the videos that we're already loading.

Just look at the settings menu. There are options for both playlists. The "4k playlist" videos have 1080 versions.

Closing this ticket since it seems there's nothing to do :-)

**Comment by cachapa** [comment]
Looks like I was mistaken. There was a new collection released with tvOS12:
https://sylvan.apple.com/Aerials/resources.tar

**Comment by DJay-X** [comment]
@cachapa First, thanks for your work. Großes Dankeschön. ;) 
Wouldn't want to miss it. Works great on my ZTE Spro 2 Smart Projector with Android 4.4.4.
Any chance to see ongoing development and all the new Videos?
Maybe the Aerial Screensaver for macOS is a good resource, too. https://github.com/JohnCoates/Aerial/releases

Thanks again for your work and the time you are investing.

**Comment by omair94** [comment]
Would also like the HDR versions as an option as well

**Comment by cachapa** [comment]
Unfortunately HDR videos are unsupported by the video player library, at least on my system (Shield).

**Comment by cachapa** [comment]
Implemented in latest release
