### ISSUE TITLE
[Request] Immersive mode

### ISSUE THREAD

**Issue by filipinascimento** [cachapa/AerialDream#2]
Currently, the view is not fully immersive and keeps a border where the buttons are. Can this be enabled by default?

https://developer.android.com/training/system-ui/immersive.html

**Comment by cachapa** [comment]
Sorry for not responding to this earlier.
The app wasn't really made for mobile devices. Beware that the entire video library is around 10GB, and that's if you're caching the videos. You can easilly destroy your entire mobile data allowance if you keep the app on.

I'll consider adding immersive mode, but first I have to build in a mechanism to avoid downloading videos on mobile networks.

**Comment by cachapa** [comment]
On second thought, immersive mode doesn't make much sense since the screensaver always works in full screen. I'll set the statusbar to hide when testing the screensaver, but a real immersive screen is out of scope.
