### ISSUE TITLE
Doesn't work on Shield at all

### ISSUE THREAD

**Issue by vistalba** [cachapa/AerialDream#20]
I just got a new nVidia Shield. OS is updated to the latest avaiable verseion.
I downloaded AerialDream from the AppStore and it doesn't work at all.

I tried with different settings like 4k, 1080p and so on...
If I select "Start.." from the settings screen it just load for around 1 second and goes back to settings screen.
If I start screensaver from Android Settings nothing happens.

Any hints how to get it work?

**Comment by omair94** [comment]
Turn off caching. Unfortunately caching doesn't work on the Shield in the latest version of the app.

**Comment by cachapa** [comment]
Fixed by disabling caching.
