### ISSUE TITLE
Replace fade transitions with something else

### ISSUE THREAD

**Issue by cachapa** [cachapa/AerialDream#30]
The fade transition requires loading and playing two videos simultaneously which isn't supported in many devices in current use.

This needs to be rewritten so that only one video is loaded at a time, and a different transition must be found between videos.

**Comment by Dreamescaper** [comment]
Just an idea: 
Use same fade transition, but use last frame from the second video instead of video itself.

**Comment by AlexDemzz** [comment]
is it fix yet ?

**Comment by N0rdmann** [comment]
Maybe just give an option to disable the transition for the time being?
I rather have a little pause between two vids than no 4K videos at all on my XH90 😥

**Comment by cachapa** [comment]
If only it would be that easy. The fade transitions are hardcoded and essentially require a rewrite of large portions just to get them out, not to mention making them configurable.

**Comment by Dreamescaper** [comment]
I have a working version without fade transition, I can submit the PR if that's acceptable.

Making it configurable is much harder indeed though.

**Comment by cachapa** [comment]
@Dreamescaper sounds good, I'd be happy to review your PR.
