### ISSUE TITLE
4k stream urls wrong/outdated?

### ISSUE THREAD

**Issue by N0rdmann** [cachapa/AerialDream#31]
1st off: Thx for this great app, seems to be the only one for AndroidTV and runs fine on my Sony Bravia XH90 ♥

When selecting 4k streams for each AppleTV year it only works once out of ~10 tests so I assume for some years the 4k streams are broken... As it does not display which year its currently trying to display I cant provide much more information :(

**Comment by cachapa** [comment]
I remember some streams not working properly due to codec or video memory issues (Aerial Dream opens two streams simultaneously), so it might not be an issue of broken URLs.
Closing this since it's more likely a loading issue being tracked in #30
