### ISSUE TITLE
is there a way to build an application from the repository?

### ISSUE THREAD

**Issue by mshakurov** [cachapa/AerialDream#45]
I apologize for such a question. But if there is an open source repository with gradle files, then perhaps there is a way to build an application from it?
I tried to build, but I get an error:

```
./gradlew build

...

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> kotlin.KotlinNullPointerException (no error message)
```

**Comment by cachapa** [comment]
The project hasn't been updated in a long while and is no longer compatible with modern versions of the build tools.

If you want to build the project you'll have to either use older tooling or update the project dependencies.

My recommendation though is to use one of the multiple other projects similar to this that are better maintained.
