### ISSUE TITLE
Caching Option

### ISSUE THREAD

**Issue by nayrnet** [cachapa/AerialDream#5]
With the new options window can we get option for caching again? My 500GB ShieldTV has plenty of space.. just an option to toggle the behavior of v0.4?

Mine auto updated and I didnt realize it was streaming it all now until I saw it stuttering when I had a big internet transfer going on.. I much prefer keeping a local copy on devices that can accommodate it.

**Comment by cachapa** [comment]
It's in the plans, but I currently don't have much time to work on it.
I'd gladly accept pull requests for that functionality though.

**Comment by cachapa** [comment]
Ok so I figured out that the player we're using has a built-in caching mechanism.
I'll add an option to use it in the next release.

**Comment by nayrnet** [comment]
ah sweet.. thank you.

**Comment by cachapa** [comment]
Ok it's done. It's currently published on the beta channel and if it works properly I'll release it sometime during the next week
